data = [{"name": "Cristiano Ronaldo", "followers": 625, "job": "Footballer", "country": "Portugal"},
    {"name": "Lionel Messi", "followers": 490, "job": "Footballer", "country": "Argentina"},
    {"name": "Selena Gomez", "followers": 429, "job": "Singer/Actress", "country": "USA"},
    {"name": "Kylie Jenner", "followers": 400, "job": "Model/Entrepreneur", "country": "USA"},
    {"name": "Dwayne Johnson", "followers": 395, "job": "Actor/Wrestler", "country": "USA"},
    {"name": "Ariana Grande", "followers": 380, "job": "Singer/Actress", "country": "USA"},
    {"name": "Kim Kardashian", "followers": 365, "job": "TV Personality/Entrepreneur", "country": "USA"},
    {"name": "Beyoncé", "followers": 320, "job": "Singer", "country": "USA"},
    {"name": "Davido", "followers": 45, "job": "Singer", "country": "Nigeria"},
    {"name": "Wizkid", "followers": 35, "job": "Singer", "country": "Nigeria"},
    {"name": "Burna Boy", "followers": 32, "job": "Singer", "country": "Nigeria"},
    {"name": "Tiwa Savage", "followers": 18, "job": "Singer", "country": "Nigeria"},
    {"name": "Yemi Alade", "followers": 17, "job": "Singer", "country": "Nigeria"},
    {"name": "Genevieve Nnaji", "followers": 12, "job": "Actress", "country": "Nigeria"},
    {"name": "Omotola Jalade", "followers": 10, "job": "Actress", "country": "Nigeria"},
    {"name": "Funke Akindele", "followers": 15, "job": "Actress", "country": "Nigeria"},
    {"name": "Don Jazzy", "followers": 14, "job": "Music Producer", "country": "Nigeria"},
    {"name": "Peter Okoye", "followers": 11, "job": "Singer", "country": "Nigeria"},
    {"name": "Paul Okoye", "followers": 10, "job": "Singer", "country": "Nigeria"},
    {"name": "Olamide", "followers": 13, "job": "Rapper", "country": "Nigeria"},
    {"name": "Basketmouth", "followers": 9, "job": "Comedian", "country": "Nigeria"},
    {"name": "AY Makun", "followers": 8, "job": "Comedian", "country": "Nigeria"},
    {"name": "Linda Ikeji", "followers": 7, "job": "Blogger", "country": "Nigeria"},
    {"name": "Cuppy", "followers": 6, "job": "DJ", "country": "Nigeria"},
    {"name": "Tunde Ednut", "followers": 8, "job": "Blogger", "country": "Nigeria"},
    {"name": "Mercy Johnson", "followers": 9, "job": "Actress", "country": "Nigeria"},
    {"name": "Priyanka Chopra", "followers": 89, "job": "Actress", "country": "India"},
    {"name": "Deepika Padukone", "followers": 75, "job": "Actress", "country": "India"},
    {"name": "Shah Rukh Khan", "followers": 50, "job": "Actor", "country": "India"},
    {"name": "Virat Kohli", "followers": 265, "job": "Cricketer", "country": "India"},
    {"name": "Jisoo", "followers": 75, "job": "Singer", "country": "South Korea"},
    {"name": "Lisa", "followers": 96, "job": "Singer", "country": "South Korea"},
    {"name": "Jennie", "followers": 80, "job": "Singer", "country": "South Korea"},
    {"name": "Rosé", "followers": 78, "job": "Singer", "country": "South Korea"},
    {"name": "Jungkook", "followers": 80, "job": "Singer", "country": "South Korea"},
    {"name": "Kim Taehyung (V)", "followers": 85, "job": "Singer", "country": "South Korea"},
    {"name": "Gigi Hadid", "followers": 80, "job": "Model", "country": "USA"},
    {"name": "Zendaya", "followers": 160, "job": "Actress", "country": "USA"},
    {"name": "Kendall Jenner", "followers": 290, "job": "Model", "country": "USA"},
    {"name": "Drake", "followers": 140, "job": "Rapper", "country": "Canada"},
    {"name": "Justin Bieber", "followers": 290, "job": "Singer", "country": "Canada"},
    {"name": "The Rock", "followers": 395, "job": "Actor", "country": "USA"},
    {"name": "Nicki Minaj", "followers": 230, "job": "Rapper", "country": "USA"},
    {"name": "Taylor Swift", "followers": 280, "job": "Singer", "country": "USA"},
    {"name": "LeBron James", "followers": 160, "job": "Basketball Player", "country": "USA"},
    {"name": "Kevin Hart", "followers": 180, "job": "Comedian/Actor", "country": "USA"},
    {"name": "Oprah Winfrey", "followers": 100, "job": "TV Host/Entrepreneur", "country": "USA"},
    {"name": "Will Smith", "followers": 75, "job": "Actor", "country": "USA"},
    {"name": "Chris Hemsworth", "followers": 80, "job": "Actor", "country": "Australia"},
    {"name": "Hugh Jackman", "followers": 40, "job": "Actor", "country": "Australia"},
    {"name": "Chris Evans", "followers": 60, "job": "Actor", "country": "USA"},
    {"name": "Robert Downey Jr.", "followers": 65, "job": "Actor", "country": "USA"},
    {"name": "Regina Daniels", "followers": 12, "job": "Actress", "country": "Nigeria"},
    {"name": "Rema", "followers": 25, "job": "Singer", "country": "Nigeria"},
    {"name": "Asisat Oshoala", "followers": 4, "job": "Footballer", "country": "Nigeria"},
    {"name": "Victor Osimhen", "followers": 5, "job": "Footballer", "country": "Nigeria"},
    {"name": "John Obi Mikel", "followers": 3, "job": "Footballer", "country": "Nigeria"},
    {"name": "Tems", "followers": 10, "job": "Singer", "country": "Nigeria"},
    {"name": "Mayorkun", "followers": 8, "job": "Singer", "country": "Nigeria"},
    {"name": "Adekunle Gold", "followers": 9, "job": "Singer", "country": "Nigeria"},
    {"name": "Simi", "followers": 8, "job": "Singer", "country": "Nigeria"},
    {"name": "Falz", "followers": 7, "job": "Rapper/Actor", "country": "Nigeria"},
    {"name": "Mr Eazi", "followers": 6, "job": "Singer", "country": "Nigeria"},
    {"name": "Patoranking", "followers": 7, "job": "Singer", "country": "Nigeria"},
    {"name": "Phyno", "followers": 6, "job": "Rapper", "country": "Nigeria"},
    {"name": "Tacha", "followers": 4, "job": "Reality TV Star", "country": "Nigeria"},
    {"name": "Ebuka Obi-Uchendu", "followers": 5, "job": "TV Host", "country": "Nigeria"}]